# Generated by Django 5.0.7 on 2024-08-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillSetParent', models.IntegerField()),
                ('skillName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='skillSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillSetName', models.CharField(max_length=255)),
            ],
        ),
    ]
