# Generated by Django 5.0.7 on 2024-08-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolio', '0002_delete_skillset_remove_skill_skillsetparent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectName', models.CharField(max_length=255)),
                ('ProjectLink', models.URLField()),
                ('ProjectPreview', models.ImageField(upload_to='')),
            ],
        ),
    ]
