# Generated by Django 5.0.7 on 2024-08-03 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolio', '0003_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='ProjectLink',
            new_name='projectLink',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='ProjectName',
            new_name='projectName',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='ProjectPreview',
            new_name='projectPreview',
        ),
    ]
