# Generated by Django 5.0.7 on 2024-08-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolio', '0004_rename_projectlink_project_projectlink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectDescription',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectPreview',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
