# Generated by Django 5.0.7 on 2024-08-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolio', '0005_project_projectdescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectContributors',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='projectTechStack',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
