# Generated by Django 5.0.7 on 2024-08-03 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolio', '0006_project_projectcontributors_project_projecttechstack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='projectContributors',
        ),
    ]
