# Generated by Django 5.0.7 on 2024-08-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolio', '0007_remove_project_projectcontributors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectPreview',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
