# Generated by Django 5.0.7 on 2024-08-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolio', '0008_alter_project_projectpreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectFeatured',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
