# Generated by Django 5.0.7 on 2026-02-12 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolio', '0010_alter_skill_skillset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
